#!/usr/bin/env python3
"""Generate docs/TEMPLATE_INDEX.md from templates/*.xml."""

from __future__ import annotations

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = "RapalS/UNRAID_DOCKER_TEMPLATES"
BRANCH = "main"
SKIP_PREFIX = "_"
INDEX_PATH = Path("docs/TEMPLATE_INDEX.md")
README_PATH = Path("README.md")
BADGE_START = "<!-- template-count-badge -->"
BADGE_END = "<!-- /template-count-badge -->"


def render_badge_line(count: int) -> str:
    return (
        f'  <a href="docs/TEMPLATE_INDEX.md">'
        f'<img src="https://img.shields.io/badge/Templates-{count}-ff8c2f?style=for-the-badge" '
        f'alt="Templates: {count}" height="28" /></a>'
    )


def update_readme_badge(readme_text: str, count: int) -> str:
    badge_line = render_badge_line(count)
    block = f"{BADGE_START}\n{badge_line}\n{BADGE_END}"
    pattern = re.compile(
        re.escape(BADGE_START) + r".*?" + re.escape(BADGE_END),
        re.DOTALL,
    )
    if not pattern.search(readme_text):
        raise ValueError(f"README.md missing {BADGE_START} ... {BADGE_END} markers")
    return pattern.sub(block, readme_text, count=1)


def text_of(root: ET.Element, tag: str) -> str:
    el = root.find(tag)
    if el is None or el.text is None:
        return ""
    return el.text.strip()


def find_doc(name: str, apps_dir: Path) -> str | None:
    exact = apps_dir / f"{name}.md"
    if exact.exists():
        return f"docs/apps/{name}.md"

    matches: list[str] = []
    for doc in sorted(apps_dir.glob("*.md")):
        if doc.name == "README.md":
            continue
        stem = doc.stem
        if name == stem or name.startswith(f"{stem}-"):
            matches.append(f"docs/apps/{stem}.md")

    if len(matches) == 1:
        return matches[0]
    return None


def parse_template(path: Path) -> dict[str, str]:
    root = ET.parse(path).getroot()
    ports: list[str] = []
    for cfg in root.findall("Config"):
        if cfg.get("Type") == "Port":
            port = (cfg.get("Default") or cfg.get("Target") or "").strip()
            if port and port not in ports:
                ports.append(port)

    repository = text_of(root, "Repository")
    image_ref = repository.split(":")[0] if repository else ""

    return {
        "file": path.name,
        "name": text_of(root, "Name") or path.stem,
        "repository": repository,
        "image_ref": image_ref,
        "category": text_of(root, "Category"),
        "ports": ", ".join(ports),
    }


def collect_entries(repo_root: Path) -> list[dict[str, str]]:
    templates_dir = repo_root / "templates"
    apps_dir = repo_root / "docs" / "apps"
    entries: list[dict[str, str]] = []

    for path in sorted(templates_dir.glob("*.xml")):
        if path.name.startswith(SKIP_PREFIX):
            continue
        entry = parse_template(path)
        doc = find_doc(entry["name"], apps_dir)
        entry["doc"] = doc or ""
        entries.append(entry)

    return entries


def render_index(entries: list[dict[str, str]]) -> str:
    lines = [
        "# Template index",
        "",
        "> Auto-generated by `python scripts/generate_template_index.py`. Do not edit by hand.",
        "",
        f"**{len(entries)}** installable template(s) live in [`templates/`](../templates/).",
        "Add this repository under **Docker → Docker Repositories** to install any of them:",
        "",
        "```",
        f"https://github.com/{REPO}",
        "```",
        "",
        "| Template | Image | Category | Ports | Setup guide |",
        "|----------|-------|----------|-------|-------------|",
    ]

    for entry in entries:
        doc_cell = f"[Guide]({entry['doc']})" if entry["doc"] else "—"
        image_cell = f"`{entry['image_ref']}`" if entry["image_ref"] else "—"
        lines.append(
            f"| [{entry['name']}](../templates/{entry['file']}) "
            f"| {image_cell} | {entry['category'] or '—'} | {entry['ports'] or '—'} | {doc_cell} |"
        )

    lines.extend(["", "## Raw install URLs", ""])
    for entry in entries:
        lines.append(
            f"- **{entry['name']}**: "
            f"`https://raw.githubusercontent.com/{REPO}/{BRANCH}/templates/{entry['file']}`"
        )

    lines.append("")
    return "\n".join(lines)


def write_index(repo_root: Path, content: str) -> Path:
    out_path = repo_root / INDEX_PATH
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8", newline="\n")
    return out_path


def write_readme_badge(repo_root: Path, count: int) -> Path:
    readme_path = repo_root / README_PATH
    readme_text = readme_path.read_text(encoding="utf-8")
    updated = update_readme_badge(readme_text, count)
    readme_path.write_text(updated, encoding="utf-8", newline="\n")
    return readme_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate docs/TEMPLATE_INDEX.md from templates/")
    parser.add_argument("--repo-root", default=".", help="Repository root directory")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if docs/TEMPLATE_INDEX.md is out of date",
    )
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    entries = collect_entries(repo_root)
    content = render_index(entries)
    out_path = repo_root / INDEX_PATH

    if args.check:
        stale = False
        if not out_path.exists():
            print(f"Missing {INDEX_PATH}. Run: python scripts/generate_template_index.py", file=sys.stderr)
            stale = True
        else:
            existing = out_path.read_text(encoding="utf-8")
            if existing != content:
                print(f"{INDEX_PATH} is out of date. Run: python scripts/generate_template_index.py", file=sys.stderr)
                stale = True

        readme_path = repo_root / README_PATH
        if not readme_path.exists():
            print(f"Missing {README_PATH}.", file=sys.stderr)
            stale = True
        else:
            expected_readme = update_readme_badge(readme_path.read_text(encoding="utf-8"), len(entries))
            if readme_path.read_text(encoding="utf-8") != expected_readme:
                print(
                    f"{README_PATH} template badge is out of date. Run: python scripts/generate_template_index.py",
                    file=sys.stderr,
                )
                stale = True

        if stale:
            return 1
        print(f"OK   {INDEX_PATH} and README badge are up to date ({len(entries)} template(s))")
        return 0

    written = write_index(repo_root, content)
    write_readme_badge(repo_root, len(entries))
    rel = written.relative_to(repo_root)
    print(f"Wrote {rel} and updated README badge ({len(entries)} template(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
